<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Octokit" Version="8.0.0" />
    <PackageReference Include="SharpCompress" Version="0.34.0" />
    <PackageReference Include="WindowsAPICodePack-Shell" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MVVMGenerator\MVVMGenerator\MVVM.Generator.csproj" OutputItemType="analyzer" />
  </ItemGroup>

</Project>
